### ISSUE TITLE
Site Vulca down

### ISSUE THREAD

**Issue by nicolasdb** [Vulca/coreTeam#2]
## context: 
I wanted to check some content on the website but the link is dead. 

## proposition. 

It seems most probably that the hosting is not paid. 
December bills, hohoho

![image](https://user-images.githubusercontent.com/12049360/49697063-023bee80-fbb3-11e8-82aa-d8b078428502.png)

**Comment by AlexandreRousselet** [comment]
Ok dude, I contact Nicolas Fifre. 
We have to pay the serveur.

**Comment by nicolasdb** [comment]
still dead

**Comment by nicolasdb** [comment]
@AlexandreRousselet @Thomas0sanz 
Website still down

![image](https://user-images.githubusercontent.com/12049360/50149921-c5f84480-02bc-11e9-895c-c5e863287afc.png)

**Comment by nicolasdb** [comment]
merci @nififre 
le site est à nouveau en ligne 🥇
